apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-container
        image: slavitriples01/devops-project:latest
        ports:
        - containerPort: 5173
